version: "3.9"

services:
  postgresql:
    container_name: postgres
    image: postgres:14
    environment:
      POSTGRES_DB: scrapper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  liquibase-migrations:
    container_name: liquibase
    image: liquibase/liquibase:4.18
    restart: on-failure
    depends_on:
      - postgresql
    command:
      - --hub-mode=off
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgres:5432/scrapper
      - --username=postgres
      - --password=postgres
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend

  rabbitmq:
    container_name: rabbitmq
    image: 'rabbitmq:3.6-management-alpine'
    volumes:
      - rabbitmq:/var/lib/rabbitmq/data
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      AMQP_URL: "AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5"
    networks:
      - backend
volumes:
  postgres-data:
  rabbitmq:

networks:
  backend:
    driver: bridge
