scrape_configs:
  - job_name: scrapper_metrics
    metrics_path: /metrics
    static_configs:
      - targets: [ 'host.docker.internal:8081' ]
  - job_name: bot_metrics
    metrics_path: /metrics
    static_configs:
      - targets: [ 'host.docker.internal:8082' ]
