name: Bot CI with Maven

on:
  push:
    paths:
        - .github/workflows/bot.yml
        - ru.tinkoff/java/bot**
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
      
env:
  TOKEN: ${{secrets.TOKEN}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Set up java
        uses: actions/setup-java@3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn package -pl bot -am

      - name: Build Docker image
        run: docker build --file bot.Dockerfile -t bot .
