name: Bot CI with Maven

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/bot.yml
      - ru.tinkoff/java/bot**
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  packages: write
env:
  token: ${{ secrets.TOKEN }}
  username: ${{ secrets.DOCKER_USERNAME }}
  password: ${{ secrets.DOCKER_PASSWORD }}

jobs:  
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ru.tinkoff/java
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
        
      - name: List files
        run: ls -a
        
      - name: Build Maven project
        run: mvn package -pl bot -am

      - name: Build Docker image
        run: docker build --build-arg bot_token=$token --file bot.Dockerfile -t bot .
        
      - name: login to Docker hub
        run: docker login -u $username -p $password
        
      - name: Push image to hub
        run: docker push bot:latest
