name: Scrapper CI with Maven

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/scrapper.yml
      - ru.tinkoff/java/scrapper**
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  packages: write
env:
  module_name: scrapper

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ru.tinkoff/java
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          
      - name: Docker Compose up
        run: docker-compose up -d
     
      - name: Build Maven project
        run: mvn package -pl $module_name -am      

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: string
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository }}

      - name: Build Docker image
        run: docker build --file $module_name.Dockerfile -t ghcr.io/${{ steps.string.outputs.lowercase }}/$module_name .

      - name: push Docker image
        run: docker push ghcr.io/${{ steps.string.outputs.lowercase }}/$module_name:latest
  
  
  checkstyle:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ru.tinkoff/java
    steps:
      - uses: actions/checkout@v3
      - name: Check module bot on code style
        run: mvn -pl $module_name -am checkstyle:check
